GET http://localhost:3000/articles
###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "second",
  "content": "article"
}
###
GET http://localhost:3000/comments?article_id=1
###
POST http://localhost:3000/comments
Content-Type: application/json

{
  "content": "heyy",
  "article_id": 1
}
###
GET http://localhost:3000/replies

###
POST http://localhost:3000/replies
Content-Type: application/json

{
  "content": "hey",
  "comment_id": 2
}
