GET http://localhost:3000/articles
###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "developper en ruby",
  "content": "c'est facile"
}
###


GET http://localhost:3000/users

###

DELETE http://localhost:3000/users/2

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "pseudo":"leo",
  "email": "leo.wattier@gmail.fr",
  "password":"password"
}

###

POST http://localhost:3000/likes
Content-Type: application/json

{
  "article_id": 1
}

###
GET http://localhost:3000/comments?article_id=1
###
POST http://localhost:3000/comments
Content-Type: application/json

{
  "content": "Premier commentaire",
  "article_id": 1
}
###
PUT http://localhost:3000/comments/3
Content-Type: application/json

{
  "content": "salu"
}
###
GET http://localhost:3000/replies

###
POST http://localhost:3000/replies
Content-Type: application/json

{
  "content": "hey",
  "comment_id": 2
}

###
GET http://localhost:3000/categories/1

###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "ruby"
}
